kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: postgres-db
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
