apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo
  labels:
    app: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
